### ISSUE TITLE
Top Menu issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#172]
Top left menu:
- [x]  Cow should be 1/2 cow coming in from left
- [x] Harvester text is wrong font size - 14 px

Harvester:
![image](https://user-images.githubusercontent.com/11514927/98599201-d93da000-2298-11eb-97e5-cb60cf5915f9.png)

Cluster Explorer:
![image](https://user-images.githubusercontent.com/11514927/98599245-e9557f80-2298-11eb-93ed-4bc1450c8575.png)

Left menu pane:
- [x] Rename "Home" to "Dashboard"
![image](https://user-images.githubusercontent.com/11514927/98732328-3a7a7780-235c-11eb-8564-d90cb53b7838.png)

**Comment by DaiYuzeng** [comment]
1. Set logo position to left: -28px (the cow's width is 56px)
2. Set font size to 14px
3. Rename "Home" to "Dashboard"
![截屏2020-11-12 上午10 49 02](https://user-images.githubusercontent.com/15041915/98889323-b0a1ea00-24d4-11eb-8017-6ca80eff897d.png)

**Comment by DaiYuzeng** [comment]
~Set logo position to left: -28px (the cow's width is 56px)~

Use new logo named "half-logo.svg"

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/193

**Comment by tfiduccia** [comment]
Verified after close

**Comment by yasker** [comment]
Thanks @tfiduccia.
