### ISSUE TITLE
Redesign home page to be a Dashboard

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#176]
The home page needs to be changed to full Dashboard:  We should probably discuss what info you would like to see in each section but I took a first shot:

![image](https://user-images.githubusercontent.com/11514927/98744972-e11c4380-236f-11eb-8415-94cffbea7788.png)

**Comment by yasker** [comment]
This dashboard LGTM. Except I don't have ideas on what to show on the top most row. @guangbochen ?

**Comment by guangbochen** [comment]
sure this is LGTM, we can skip the top panel for now and uses the same color for the instrument panel of CPU memory and storage,

**Comment by tfiduccia** [comment]
@guangbochen @yasker There isn't any host specific things you would like to show?  You can put a list of IPs, OS, OS image, k8s version?  Would each host have different info (beside ips?).

**Comment by WuJun2016** [comment]
no suitable information to show on the top

**Comment by tfiduccia** [comment]
Fixed.  Looks great!
