### ISSUE TITLE
Icons are not correct?

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#183]
- [x] The icons in the Action menu are not the same ones we are using?
![image](https://user-images.githubusercontent.com/11514927/98869254-ba711200-242e-11eb-814f-43b3871d389e.png)

- [x] We aren't using icons on the Left menu pane?  Should these be here?
![image](https://user-images.githubusercontent.com/11514927/98869309-cf4da580-242e-11eb-84a9-8486eb8a25df.png)

**Comment by DaiYuzeng** [comment]
1. The icons provided by Dashboard, except the migrate icon, we will change it.
2. We will revert the left menu changes to follow dashboard style.

**Comment by guangbochen** [comment]
@DaiYuzeng can u please help to provide a screenshot of how the menu looks like with having and not having the icons, thanks.

**Comment by DaiYuzeng** [comment]
@guangbochen 

#### With icons
![image](https://user-images.githubusercontent.com/15041915/99236778-93ea1700-2832-11eb-8299-6415d7542350.png)

#### Only labels
![image](https://user-images.githubusercontent.com/15041915/99236804-9d737f00-2832-11eb-9cdf-431de5000f2a.png)

#### Stick in Dashboard style
_(but there is not concept of namespace in harvester)_

![image](https://user-images.githubusercontent.com/15041915/99237469-779aaa00-2833-11eb-8944-3e0db2d47cb2.png)

**Comment by guangbochen** [comment]
would prefer to keep the icons but with the proper design changes, cc @tfiduccia @lvuch can u please to provide some icons for the left-menu since the dashboard style is not applicable, thanks.

**Comment by DaiYuzeng** [comment]
In the end we choose only labels. @tfiduccia

**Comment by tfiduccia** [comment]
Fixed - Looks great!
