### ISSUE TITLE
Create Template UI polish

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#184]
- [x] This should be exactly the same as Create Virtual Machine.

- [x] Only show "Set as Default" checkbox on the creation of more then 1 version.

**Comment by vincent99** [comment]
"Use as default" isn't which one of the templates is the default...  It's which version within a single template is the default.  That checkbox makes sense for adding an additional version to a template, but is implied/always true when making the first one so it just doesn't need to be shown.

This all works similar to RKE Templates in the Ember UI.. so you might want the same thing where the list of templates shows the actual *versions* as rows, grouped by their parent *template*.  That gives you a place to put the action to set which version is the default, delete a particular version, etc, which there's seemingly no place to right now.
