### ISSUE TITLE
Settings list page 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#188]
- [x] Make the settings page match the one we have for Cluster Manager (remove Age, add Value field to table and show the value for that setting)  We have a component you should be using for this... connect with Vincent.

Table and list page should look like this:
![image](https://user-images.githubusercontent.com/11514927/98876207-01650480-243b-11eb-81aa-d1ad551726c9.png)

**Comment by vincent99** [comment]
The one in Rancher is just a generic view from the custom resource definition.  You can edit your CRD to include value as one of the printer columns so that it shows up in `kubectl get ...` too.

**Comment by tfiduccia** [comment]
Verified fixed
