### ISSUE TITLE
Create Image UI polish

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#190]
- [x] Put Image Name & Description on top (use name/description component)
- [x] Put Url field on second line
- [x] Take Label & Annotation out of tabs and move them below URL, like this (there might be a component for this?):
![image](https://user-images.githubusercontent.com/11514927/98876540-c0212480-243b-11eb-93b8-84c58cec43d7.png)

**Comment by DaiYuzeng** [comment]
Hi @tfiduccia ! There is the screenshot of new UI.

![截屏2020-11-24 上午11 04 08](https://user-images.githubusercontent.com/15041915/100041764-fb145680-2e44-11eb-8adf-64b6a6743caf.png)

**Comment by tfiduccia** [comment]
looks good
