### ISSUE TITLE
Redesign Login page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#198]
The login page is not consistent with our new login.  
@lvuch - will give you mocks

**Comment by DaiYuzeng** [comment]
There are screenshots of the login page.

Need your comments. @lvuch @tfiduccia 

Thanks!

![截屏2020-12-02 下午5 35 30](https://user-images.githubusercontent.com/15041915/100992749-843b3400-358f-11eb-8f1a-7c6d8cf1b6c5.png)
![截屏2020-12-02 下午5 29 13](https://user-images.githubusercontent.com/15041915/100992767-8a311500-358f-11eb-8eb6-5370e1edf014.png)
![截屏2020-12-02 下午5 29 21](https://user-images.githubusercontent.com/15041915/100992785-8e5d3280-358f-11eb-85e6-ff078890731c.png)
![截屏2020-12-02 下午5 29 47](https://user-images.githubusercontent.com/15041915/100992809-95844080-358f-11eb-94e7-0eeacfe6538f.png)

**Comment by tfiduccia** [comment]
Fixed
