### ISSUE TITLE
Reorder Left Menu pane

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#199]
- Dashboard
- Hosts
- Virtual Machines 
- Volumes
- Images
- Advanced  ^ (drop-down menu - this is basically for things you set once or not often enough to show all the time)
    - VM Templates
    - Networks
    - SSH Keys
    - Users
    - Settings

Example:
![image](https://user-images.githubusercontent.com/11514927/98985446-d33a0000-24e0-11eb-860a-414f4c5d19dc.png)

**Comment by DaiYuzeng** [comment]
![截屏2020-11-13 下午3 14 34](https://user-images.githubusercontent.com/15041915/99039841-09e84700-25c3-11eb-9679-5d692d94a715.png)
![截屏2020-11-13 下午3 14 38](https://user-images.githubusercontent.com/15041915/99039844-0bb20a80-25c3-11eb-83b3-625adfb7b0df.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/203

**Comment by yasker** [comment]
@guangbochen Based on the latest screenshot, it seems the issue hasn't solved yet?

```
Dashboard
Hosts
Virtual Machines
Volumes
Images
Advanced ^ (drop-down menu - this is basically for things you set once or not often enough to show all the time)
VM Templates
Networks
SSH Keys
Users
Settings
```

The position of setting and volume is still wrong.

**Comment by DaiYuzeng** [comment]
The order is fixed.
![image](https://user-images.githubusercontent.com/15041915/99324386-10224000-28af-11eb-8482-f0ff34bcc9d5.png)

**Comment by tfiduccia** [comment]
Verified fixed
