### ISSUE TITLE
Add Edit to host 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#200]
We should add the ability to Edit the host & 

- [x] Allow a friendly name to be set

- [ ] Move the Network setting from setting into the edit host.  Each host may have it's own physical NIC so setting one globally isn't a good idea?

**Comment by yasker** [comment]
@guangbochen Is it possible for the user to set nic for each node now? I think it's OK if we require homogeneous node setup for MVP. But not sure how other cloud platforms, e.g. openstack/cloudstack expects the same.

**Comment by guangbochen** [comment]
1. for editing host, we can reference the design from the rancher UI, and allow set custom name and description should be ok for now.
![image](https://user-images.githubusercontent.com/4569037/100568154-580c8280-3305-11eb-9f8d-74bc238cf0fb.png)
1. for custom NIC config of each host will be tracked on https://github.com/rancher/harvester/issues/249

**Comment by tfiduccia** [comment]
Fixed
