### ISSUE TITLE
Networks page is always showing the error message

### ISSUE THREAD

**Issue by guangbochen** [rancher/harvester-ui#212]
The networks page is always showing the error message even if the network condition is successfully configured.

![image](https://user-images.githubusercontent.com/4569037/99354267-1fba7c80-28e1-11eb-9149-24838a39b33e.png)

**Comment by tfiduccia** [comment]
This is still showing up for me?  On both the network settings and network pages.  Even thou there is nothing in the field now.
![image](https://user-images.githubusercontent.com/11514927/99564903-3ec01980-2988-11eb-8d45-3660a31e896f.png)
![image](https://user-images.githubusercontent.com/11514927/99564968-54cdda00-2988-11eb-81cb-fcfd4eda7f6c.png)

**Comment by WuJun2016** [comment]
This is normal. Because you set an error value, there will be an error message. This issue describes that if the network setting is set correctly, no message should be prompted in the network page.

**Comment by DoNotSayYes** [comment]
Validated
