### ISSUE TITLE
websocket address error

### ISSUE THREAD

**Issue by WuJun2016** [rancher/harvester-ui#215]
Steps to reproduce:

Create a VM 
when status is not running
click serial console

![image](https://user-images.githubusercontent.com/24985926/99366858-22729d00-28f4-11eb-87e0-f54011bb4bf5.png)

**Comment by DaiYuzeng** [comment]
@WuJun2016 @DoNotSayYes ConsoleBar Dropdown is only available when VM is running.

**Comment by DoNotSayYes** [comment]
Validated
