### ISSUE TITLE
Make the window title is consistent with VM name

### ISSUE THREAD

**Issue by DaiYuzeng** [rancher/harvester-ui#228]
![image](https://user-images.githubusercontent.com/15041915/99612211-1ac80b00-2a50-11eb-947b-4da168ef27dd.png)

**Comment by DaiYuzeng** [comment]
same with #242

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/102038250-bbb4a680-3e01-11eb-81eb-a61c9526e17d.png)
